import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  zh: {
    "app.title": "Link 控制舱",
    "app.initializing": "正在初始化 Link 系统...",
    "app.currentMode": "当前状态",
    "app.refresh": "刷新数据流",
    "app.cognitive": "认知参数",
    "app.studyTotal": "学习总累计",
    "app.exerciseTotal": "体育运动量",
    "app.luoguTotal": "洛谷累计通过",
    "app.expenseTotal": "账单总支出",
    "app.incomeTotal": "账单总收入",
    "app.syncLuogu": "同步数据",
    "app.footer": "LINK // 核心链路已稳定 // 运行环境: DEEP SPACE 9",
    "timer.title": "聆光专注",
    "timer.manual": "手动补登",
    "timer.mode": "模式设定",
    "timer.forward": "正向计时",
    "timer.p25": "🍅 25分钟番茄",
    "timer.p50": "🍅 50分钟番茄",
    "timer.custom": "⚙️ 自定义倒数",
    "timer.minutes": "分钟数",
    "timer.tag": "记录标签",
    "timer.study": "📖 学习/复习",
    "timer.coding": "💻 代码/刷题",
    "timer.exercise": "🏃 健身/运动",
    "timer.reading": "📚 书籍阅读",
    "timer.customTag": "✏️ 自定义标签",
    "timer.newTag": "输入新标签名",
    "timer.date": "日期",
    "timer.start": "起",
    "timer.end": "止",
    "timer.min": "分",
    "timer.remark": "备注",
    "timer.logData": "记录数据",
    "timer.completion": "专注完成",
    "timer.briefLog": "简要记录",
    "timer.discard": "作废",
    "timer.saveLog": "保存记录",
    "timer.setTag": "设定标签",
    "timer.xMinPomodoro": "{x}分钟番茄",
    "chat.title": "LINK 通信终端",
    "chat.thinking": "思考中...",
    "chat.input": "发送消息，Link 将更新实体记忆库...",
    "chat.memoryCore": "LINK 活跃记忆核心",
    "chat.emptyMemory": "记忆区空白。闲聊分享您的心事和目标后，智脑将自动提取并关联。",
    "chat.wipe": "是否确认从 Link 智脑记忆区中擦除这片数据？",
    "chat.wipeBtn": "擦除本条记忆",
    "settings.title": "系统设置",
    "settings.lifeMode": "模式/状态",
    "settings.currentPeriod": "当前模式/状态",
    "settings.modeHint": "切换模式将自适应更改自律标准、AI 管家语气及推送阈值",
    "settings.uid": "洛谷 UID",
    "settings.solved": "已计洛谷累计数",
    "settings.aiKey": "智能与 API 密钥",
    "settings.deepseek": "DeepSeek API Key (主人心事记忆对话)",
    "settings.deepseekHint": "本配置保存在本地 SQLite 中，仅用于本地 AI 对话和日记点评",
    "settings.push": "推送通道",
    "settings.pushTime": "推送时间",
    "settings.dailyPush": "开启每日推送",
    "settings.barkKey": "iOS Bark Device Key (选填)",
    "settings.pushDeerKey": "微信 PushDeer PushKey (选填)",
    "settings.createCustom": "创建自定义模式",
    "settings.saveConfig": "保存配置",
    "settings.registry": "模式列表",
    "settings.createTitle": "创建新生命模式",
    "settings.modeId": "模式英文代号 (唯一)",
    "settings.modeName": "模式展示名称",
    "settings.desc": "描述说明",
    "settings.targetStudy": "目标学习(分钟)",
    "settings.targetExercise": "目标运动(分钟)",
    "settings.targetLuogu": "目标过题(题)",
    "settings.allowPush": "在此模式下允许微信/手机催促提醒",
    "settings.aiPrompt": "Link 智脑语气指导提示词",
    "settings.cancel": "取消",
    "settings.create": "创建模式",
    "heatmap.title": "认知热力图",
    "heatmap.addEvent": "未来日程",
    "heatmap.combined": "🔥 综合活跃",
    "heatmap.luogu": "💻 洛谷刷题",
    "heatmap.study": "📖 学习时间",
    "heatmap.exercise": "🏃 体育健身",
    "heatmap.hint": "光格代表当天活跃度：越深越自律 (虚线为未来规划)",
    "heatmap.countdown": "倒计时: {days} 天",
    "heatmap.addMilestone": "添加里程碑",
    "heatmap.targetDate": "目标日期",
    "heatmap.eventName": "事件名称 (如 六级考试)",
    "heatmap.eventDesc": "备注详情",
    "heatmap.addEventBtn": "添加事件",
    "ledger.title": "收支流水终端",
    "ledger.expense": "支出",
    "ledger.income": "收入",
    "ledger.amount": "流水金额(元)",
    "ledger.category": "账单分类",
    "ledger.date": "发生日期",
    "ledger.desc": "说明备注",
    "ledger.save": "保存记录",
    "ledger.uploadTitle": "微信 / 支付宝账单 CSV 导入",
    "ledger.uploadDesc": "拖拽或点击上传 CSV 文件进行智能分类解析",
    "ledger.parsing": "正在解析 CSV 账单数据...",
    "ledger.recent": "近期流水 (最新15条)",
    "ledger.empty": "舱室内暂无账单数据流",
    "stats.title": "高级进阶统计",
    "stats.daily": "日",
    "stats.weekly": "周",
    "stats.monthly": "月",
    "stats.yearly": "年",
    "stats.total": "总",
    "stats.empty": "该时段暂无专注记录",
    "stats.cumulative": "累计时段专注"
  },
  en: {
    "app.title": "Link Cockpit",
    "app.initializing": "INITIALIZING LINK SYSTEM...",
    "app.currentMode": "CURRENT STATUS",
    "app.refresh": "Refresh Data Stream",
    "app.cognitive": "COGNITIVE CAPACITIES",
    "app.studyTotal": "Total Study",
    "app.exerciseTotal": "Total Exercise",
    "app.luoguTotal": "Luogu Solved",
    "app.expenseTotal": "Total Expense",
    "app.incomeTotal": "Total Income",
    "app.syncLuogu": "SYNC DATA",
    "app.footer": "LINK // ALL LOCAL PROCEDURES STABILIZED // OPERATIONAL ENVIRONMENT: DEEP SPACE 9",
    "timer.title": "LINK FOCUS",
    "timer.manual": "MANUAL",
    "timer.mode": "Mode",
    "timer.forward": "Forward Timer",
    "timer.p25": "🍅 25min Pomodoro",
    "timer.p50": "🍅 50min Pomodoro",
    "timer.custom": "⚙️ Custom Down",
    "timer.minutes": "Minutes",
    "timer.tag": "Tag",
    "timer.study": "📖 Study/Review",
    "timer.coding": "💻 Code/Leetcode",
    "timer.exercise": "🏃 Exercise",
    "timer.reading": "📚 Reading",
    "timer.customTag": "✏️ Custom Tag",
    "timer.newTag": "New tag name",
    "timer.date": "Date",
    "timer.start": "Start",
    "timer.end": "End",
    "timer.min": "Min",
    "timer.remark": "Remark",
    "timer.logData": "LOG DATA",
    "timer.completion": "FOCUS COMPLETION",
    "timer.briefLog": "Brief Log",
    "timer.discard": "DISCARD",
    "timer.saveLog": "SAVE LOG",
    "timer.setTag": "Set Tag",
    "timer.xMinPomodoro": "{x}min Pomodoro",
    "chat.title": "LINK COMM TERMINAL",
    "chat.thinking": "THINKING...",
    "chat.input": "Send a message, Link will update the memory core...",
    "chat.memoryCore": "LINK ACTIVE MEMORY CORE",
    "chat.emptyMemory": "Memory core is empty. Chat to share your goals and thoughts.",
    "chat.wipe": "Confirm wiping this memory from Link?",
    "chat.wipeBtn": "Wipe this memory",
    "settings.title": "SYSTEM SETTINGS",
    "settings.lifeMode": "MODE / STATUS",
    "settings.currentPeriod": "CURRENT MODE / STATUS",
    "settings.modeHint": "Switching modes changes standards, AI tone and push thresholds.",
    "settings.uid": "Luogu UID",
    "settings.solved": "Luogu Total Solved",
    "settings.aiKey": "INTELLIGENCE & API KEY",
    "settings.deepseek": "DeepSeek API Key (Local AI Chat)",
    "settings.deepseekHint": "Saved in local SQLite, used only for local AI conversation.",
    "settings.push": "PUSH CHANNELS",
    "settings.pushTime": "Push Time",
    "settings.dailyPush": "Enable Daily Push",
    "settings.barkKey": "iOS Bark Device Key (Optional)",
    "settings.pushDeerKey": "PushDeer PushKey (Optional)",
    "settings.createCustom": "CREATE CUSTOM MODE",
    "settings.saveConfig": "SAVE CONFIGURATION",
    "settings.registry": "MODE LIST",
    "settings.createTitle": "CREATE NEW LIFE MODE",
    "settings.modeId": "Mode ID (Unique)",
    "settings.modeName": "Display Name",
    "settings.desc": "Description",
    "settings.targetStudy": "Target Study (min)",
    "settings.targetExercise": "Target Exercise (min)",
    "settings.targetLuogu": "Target Luogu (solved)",
    "settings.allowPush": "Allow push reminders in this mode",
    "settings.aiPrompt": "Link AI Tone Prompt",
    "settings.cancel": "CANCEL",
    "settings.create": "CREATE MODE",
    "heatmap.title": "COGNITIVE HEATMAP",
    "heatmap.addEvent": "Add Event",
    "heatmap.combined": "🔥 Combined",
    "heatmap.luogu": "💻 Luogu",
    "heatmap.study": "📖 Study",
    "heatmap.exercise": "🏃 Exercise",
    "heatmap.hint": "Cells represent activity: darker is better (dashed for future)",
    "heatmap.countdown": "Countdown: {days} days",
    "heatmap.addMilestone": "ADD MILESTONE",
    "heatmap.targetDate": "Target Date",
    "heatmap.eventName": "Event Name",
    "heatmap.eventDesc": "Description",
    "heatmap.addEventBtn": "ADD EVENT",
    "ledger.title": "LEDGER & BILL INTERFACE",
    "ledger.expense": "EXPENSE",
    "ledger.income": "INCOME",
    "ledger.amount": "Amount",
    "ledger.category": "Category",
    "ledger.date": "Date",
    "ledger.desc": "Description",
    "ledger.save": "SAVE MANUAL RECORD",
    "ledger.uploadTitle": "WeChat / Alipay CSV Import",
    "ledger.uploadDesc": "Drag or click to upload CSV for smart parsing",
    "ledger.parsing": "PARSING CSV BILL DATA...",
    "ledger.recent": "RECENT LEDGER STREAM (LATEST 15)",
    "ledger.empty": "No bill data stream in cabin",
    "stats.title": "ADVANCED STATS",
    "stats.daily": "Daily",
    "stats.weekly": "Weekly",
    "stats.monthly": "Monthly",
    "stats.yearly": "Yearly",
    "stats.total": "Total",
    "stats.empty": "No focus records for this period",
    "stats.cumulative": "Cumulative Focus"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('link_lang') || 'zh';
  });

  useEffect(() => {
    localStorage.setItem('link_lang', lang);
  }, [lang]);

  const t = (key, params = {}) => {
    let str = translations[lang][key] || translations['zh'][key] || key;
    Object.keys(params).forEach(k => {
      str = str.replace(`{${k}}`, params[k]);
    });
    return str;
  };

  const toggleLang = () => {
    setLang(prev => prev === 'zh' ? 'en' : 'zh');
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
